[tool.poetry]
name = "projectgetbackcoach"
version = "0.1.0"
description = ""
authors = ["krimaus <krimaus01@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.115.4"}
uvicorn = "^0.32.0"
pydantic = "^2.9.2"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.36"}
alembic = "^1.13.3"
python-dotenv = "^1.0.1"
psycopg2 = "^2.9.10"
asyncpg = "^0.30.0"
httpx = "^0.28.1"

[tool.poetry.group.dev.dependencies]
pytest-asyncio = "^1.3.0"
httpx = "^0.28.1"
pytest = "^9.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["src/app/tests"]
pythonpath = ["src"]