"""Add attendance and practice tables

Revision ID: 03a3a769206d
Revises: 7320e8b701be
Create Date: 2024-11-04 21:05:37.226469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03a3a769206d'
down_revision: Union[str, None] = '7320e8b701be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('practice_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('planned_attendance', sa.Boolean(), nullable=False),
    sa.Column('actual_attendance', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('practice_id', 'user_id')
    )
    op.create_table('practice',
    sa.Column('date_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'user_type')
    op.execute("DROP TYPE usertype")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', postgresql.ENUM('COACH', 'MEMBER', name='usertype'), autoincrement=False, nullable=False))
    op.drop_table('practice')
    op.drop_table('attendance')
    # ### end Alembic commands ###
