"""Create practice series table

Revision ID: 07323c0daf1b
Revises: fbd474057811
Create Date: 2026-07-14 12:05:42.302243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07323c0daf1b'
down_revision: Union[str, None] = 'fbd474057811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_series',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days_of_week', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('start_time', sa.TIME(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIME(timezone=True), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('practice', sa.Column('description', sa.String(), nullable=True))
    op.add_column('practice', sa.Column('series_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'practice', 'practice_series', ['series_id'], ['id'])
    op.drop_column('practice', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'practice', type_='foreignkey')
    op.drop_column('practice', 'series_id')
    op.drop_column('practice', 'description')
    op.drop_table('practice_series')
    # ### end Alembic commands ###
