"""Rename practice columns to better match DTO

Revision ID: 1c3cbd17802a
Revises: 03a3a769206d
Create Date: 2025-01-04 17:00:24.516294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c3cbd17802a'
down_revision: Union[str, None] = '03a3a769206d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice', sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('practice', sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('practice', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('practice', 'date_time')
    op.drop_column('practice', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('practice', sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('practice', 'description')
    op.drop_column('practice', 'end_time')
    op.drop_column('practice', 'start_time')
    # ### end Alembic commands ###
