"""Add user_role table and enum

Revision ID: 21a81eac9a92
Revises: 1c3cbd17802a
Create Date: 2026-01-11 12:41:13.380798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

user_role_enum = postgresql.ENUM(
    'ADMIN', 'COACH', 'MEMBER',
    name='user_role_enum'
)

# revision identifiers, used by Alembic.
revision: str = '21a81eac9a92'
down_revision: Union[str, None] = '1c3cbd17802a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('user_role',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', user_role_enum, nullable=False),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
