"""Add delete cascade to practice series

Revision ID: 3e3d701a39a6
Revises: 07323c0daf1b
Create Date: 2026-07-16 09:37:36.850492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3d701a39a6'
down_revision: Union[str, None] = '07323c0daf1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('practice_series_id_fkey'), 'practice', type_='foreignkey')
    op.create_foreign_key(None, 'practice', 'practice_series', ['series_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'practice', type_='foreignkey')
    op.create_foreign_key(op.f('practice_series_id_fkey'), 'practice', 'practice_series', ['series_id'], ['id'])
    # ### end Alembic commands ###
