"""Change attendance information to be held in a JSON

Revision ID: bd3f1bdea26f
Revises: 888e9e31f810
Create Date: 2026-01-26 09:42:15.352832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3f1bdea26f'
down_revision: Union[str, None] = '888e9e31f810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('attendance_list', sa.JSON(), nullable=False))
    op.drop_column('attendance', 'planned_attendance')
    op.drop_column('attendance', 'user_id')
    op.drop_column('attendance', 'actual_attendance')
    op.add_column('practice', sa.Column('team_id', sa.Uuid(), nullable=False))
    sa.PrimaryKeyConstraint('practice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice', 'team_id')
    op.add_column('attendance', sa.Column('actual_attendance', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('attendance', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('attendance', sa.Column('planned_attendance', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('attendance', 'attendance_list')
    sa.PrimaryKeyConstraint('practice_id', 'user_id')
    # ### end Alembic commands ###
