"""Add hashed password for user and unique constraint for username

Revision ID: e94fa4bff8ef
Revises: bd3f1bdea26f
Create Date: 2026-06-29 16:40:19.883438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94fa4bff8ef'
down_revision: Union[str, None] = 'bd3f1bdea26f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('user', sa.Column('hashed_password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'hashed_password')
    op.alter_column('attendance', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
