"""Clean up practice table and add full_name to user

Revision ID: fbd474057811
Revises: d8ccc26dfadb
Create Date: 2026-07-13 11:26:43.269126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd474057811'
down_revision: Union[str, None] = 'd8ccc26dfadb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice', 'description')
    op.add_column(
        'user',
        sa.Column(
            'full_name',
            sa.String(),
            sa.Computed("last_name || ' ' || first_name", persisted=True),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'full_name')
    op.add_column('practice', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
